/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admin: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admin: Admin;
    project: Project;
    service: Service;
    'service-item': ServiceItem;
    reviews: Review;
    faq: Faq;
    blog: Blog;
    'micro-offerings': MicroOffering;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admin: AdminSelect<false> | AdminSelect<true>;
    project: ProjectSelect<false> | ProjectSelect<true>;
    service: ServiceSelect<false> | ServiceSelect<true>;
    'service-item': ServiceItemSelect<false> | ServiceItemSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'micro-offerings': MicroOfferingsSelect<false> | MicroOfferingsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'blogs-page': BlogsPage;
    'services-page': ServicesPage;
    'projects-page': ProjectsPage;
    'about-page': AboutPage;
    'seo-config': SeoConfig;
    meta: Meta;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'blogs-page': BlogsPageSelect<false> | BlogsPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'seo-config': SeoConfigSelect<false> | SeoConfigSelect<true>;
    meta: MetaSelect<false> | MetaSelect<true>;
  };
  locale: null;
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin".
 */
export interface Admin {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admin';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project".
 */
export interface Project {
  id: number;
  name: string;
  projectImage?:
    | {
        relationTo: 'media';
        value: number | Media;
      }[]
    | null;
  description: string;
  features: {
    feature: string;
    id?: string | null;
  }[];
  area: string;
  timeline: string;
  type: 'residential' | 'shops-showrooms' | 'offices' | 'restaurants';
  location: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  description: string;
  serviceThumbnail?: {
    relationTo: 'media';
    value: number | Media;
  } | null;
  serviceItems?:
    | {
        relationTo: 'service-item';
        value: number | ServiceItem;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-item".
 */
export interface ServiceItem {
  id: number;
  name: string;
  slug: string;
  description: string;
  images?:
    | {
        relationTo: 'media';
        value: number | Media;
      }[]
    | null;
  componentLayout?: string | null;
  componentDimensions?: string | null;
  specialFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  estimatedTime: string;
  estimatedCost?: string | null;
  colours?:
    | {
        colour: string;
        component: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  content: string;
  video?: {
    relationTo: 'media';
    value: number | Media;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  readingTime: string;
  description: string;
  coverImage: string;
  coverImageAlt: string;
  /**
   * Paste MDX body only. Do not include import statements or export metadata.
   */
  content: string;
  seo: {
    title: string;
    description: string;
    keywords: string;
    openGraphTitle: string;
    openGraphDescription: string;
    twitterTitle: string;
    twitterDescription: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Micro Offerings are the small services that we offer to our clients. They are not part of our main services but are offered as a separate service.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "micro-offerings".
 */
export interface MicroOffering {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admin';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'project';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'service';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-item';
        value: number | ServiceItem;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'micro-offerings';
        value: number | MicroOffering;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admin';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admin';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_select".
 */
export interface AdminSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project_select".
 */
export interface ProjectSelect<T extends boolean = true> {
  name?: T;
  projectImage?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  area?: T;
  timeline?: T;
  type?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_select".
 */
export interface ServiceSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  serviceThumbnail?: T;
  serviceItems?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-item_select".
 */
export interface ServiceItemSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  images?: T;
  componentLayout?: T;
  componentDimensions?: T;
  specialFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  estimatedTime?: T;
  estimatedCost?: T;
  colours?:
    | T
    | {
        colour?: T;
        component?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  content?: T;
  video?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  readingTime?: T;
  description?: T;
  coverImage?: T;
  coverImageAlt?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "micro-offerings_select".
 */
export interface MicroOfferingsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroHeadlinePartOne: string;
  heroHeadlinePartTwo: string;
  heroDescription: string;
  featuredProjectsSectionLabel: string;
  featuredProjectsSectionHeadlinePartOne: string;
  featuredProjectsSectionHeadlinePartTwo: string;
  featuredProjects: (number | Project)[];
  servicesSectionLabel: string;
  servicesSectionHeadlinePartOne: string;
  servicesSectionHeadlinePartTwo: string;
  servicesSectionDescription: string;
  servicesSectionStats: {
    stat: string;
    label: string;
    id?: string | null;
  }[];
  servicesSectionList: {
    serviceHeading?: string | null;
    serviceDescription?: string | null;
    serviceDeliverables?:
      | {
          relationTo: 'micro-offerings';
          value: number | MicroOffering;
        }[]
      | null;
    id?: string | null;
  }[];
  reviewsSectionLabel: string;
  reviewsSectionHeadlinePartOne?: string | null;
  reviewsSectionHeadlinePartTwo?: string | null;
  featuredReview: {
    relationTo: 'reviews';
    value: number | Review;
  };
  reviewsItems: {
    relationTo: 'reviews';
    value: number | Review;
  }[];
  faqSectionLabel: string;
  faqSectionHeadlinePartOne: string;
  faqSectionHeadlinePartTwo: string;
  faqSectionDescription: string;
  faqSectionItems: {
    relationTo: 'faq';
    value: number | Faq;
  }[];
  socialSectionLabel: string;
  socialSectionHeadlinePartOne?: string | null;
  socialSectionHeadlinePartTwo?: string | null;
  socialSectionDescription: string;
  seo: {
    title: string;
    description: string;
    keywords: string;
    canonicalPath: string;
    openGraphTitle: string;
    openGraphDescription: string;
    twitterTitle: string;
    twitterDescription: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs-page".
 */
export interface BlogsPage {
  id: number;
  title: string;
  description: string;
  seo: {
    title: string;
    description: string;
    keywords: string;
    canonicalPath: string;
    openGraphTitle: string;
    openGraphDescription: string;
    twitterTitle: string;
    twitterDescription: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  seo: {
    title: string;
    description: string;
    keywords: string;
    canonicalPath: string;
    openGraphTitle: string;
    openGraphDescription: string;
    twitterTitle: string;
    twitterDescription: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  heroHeadlinePartOne: string;
  heroHeadlinePartTwo: string;
  heroDescription: string;
  projects: (number | Project)[];
  seo: {
    title: string;
    description: string;
    keywords: string;
    canonicalPath: string;
    openGraphTitle: string;
    openGraphDescription: string;
    twitterTitle: string;
    twitterDescription: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroLabel: string;
  heroHeadlinePartOne: string;
  heroHeadlinePartTwo?: string | null;
  heroDescription: string;
  sectionTwoLabel: string;
  sectionTwoHeadline: string;
  sectionTwoDescription: {
    journeyItem: string;
    id?: string | null;
  }[];
  sectionThreeLabel: string;
  approachSectionItems: {
    approachItemTitle: string;
    approachItemDescription: string;
    id?: string | null;
  }[];
  seo: {
    title: string;
    description: string;
    keywords: string;
    canonicalPath: string;
    openGraphTitle: string;
    openGraphDescription: string;
    twitterTitle: string;
    twitterDescription: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-config".
 */
export interface SeoConfig {
  id: number;
  metadataBase: string;
  siteName: string;
  titleSuffix: string;
  defaultRobotsIndex: boolean;
  defaultRobotsFollow: boolean;
  defaultTwitterCard: 'summary' | 'summary_large_image';
  defaultOgImageUrl: string;
  defaultOgImageAlt: string;
  serviceNotFoundTitle: string;
  serviceItemNotFoundTitle: string;
  organization: {
    name: string;
    legalName: string;
    url: string;
    logoUrl: string;
    telephone: string;
    email: string;
    foundingDate: string;
    description: string;
    priceRange: string;
    founderName: string;
    founderJobTitle: string;
    addressLocality: string;
    addressRegion: string;
    addressCountry: string;
    geoLatitude: number;
    geoLongitude: number;
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
    areaServed?:
      | {
          name: string;
          type: 'City' | 'State' | 'Country';
          id?: string | null;
        }[]
      | null;
    serviceCatalog?:
      | {
          name: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meta".
 */
export interface Meta {
  id: number;
  brand: string;
  /**
   * Upload profile image for the about page.
   */
  profileImage?: {
    relationTo: 'media';
    value: number | Media;
  } | null;
  phone: string;
  whatsapp: string;
  email: string;
  insta: string;
  youtube: string;
  tagline_footer: string;
  instaFollowers: string;
  youtubeSubscribers: string;
  ownerName: string;
  ownerRole: string;
  yearOfEstablishment: number;
  headquartersLocation: string;
  googleMapsEmbed: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroHeadlinePartOne?: T;
  heroHeadlinePartTwo?: T;
  heroDescription?: T;
  featuredProjectsSectionLabel?: T;
  featuredProjectsSectionHeadlinePartOne?: T;
  featuredProjectsSectionHeadlinePartTwo?: T;
  featuredProjects?: T;
  servicesSectionLabel?: T;
  servicesSectionHeadlinePartOne?: T;
  servicesSectionHeadlinePartTwo?: T;
  servicesSectionDescription?: T;
  servicesSectionStats?:
    | T
    | {
        stat?: T;
        label?: T;
        id?: T;
      };
  servicesSectionList?:
    | T
    | {
        serviceHeading?: T;
        serviceDescription?: T;
        serviceDeliverables?: T;
        id?: T;
      };
  reviewsSectionLabel?: T;
  reviewsSectionHeadlinePartOne?: T;
  reviewsSectionHeadlinePartTwo?: T;
  featuredReview?: T;
  reviewsItems?: T;
  faqSectionLabel?: T;
  faqSectionHeadlinePartOne?: T;
  faqSectionHeadlinePartTwo?: T;
  faqSectionDescription?: T;
  faqSectionItems?: T;
  socialSectionLabel?: T;
  socialSectionHeadlinePartOne?: T;
  socialSectionHeadlinePartTwo?: T;
  socialSectionDescription?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonicalPath?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs-page_select".
 */
export interface BlogsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonicalPath?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonicalPath?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  heroHeadlinePartOne?: T;
  heroHeadlinePartTwo?: T;
  heroDescription?: T;
  projects?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonicalPath?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroLabel?: T;
  heroHeadlinePartOne?: T;
  heroHeadlinePartTwo?: T;
  heroDescription?: T;
  sectionTwoLabel?: T;
  sectionTwoHeadline?: T;
  sectionTwoDescription?:
    | T
    | {
        journeyItem?: T;
        id?: T;
      };
  sectionThreeLabel?: T;
  approachSectionItems?:
    | T
    | {
        approachItemTitle?: T;
        approachItemDescription?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonicalPath?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-config_select".
 */
export interface SeoConfigSelect<T extends boolean = true> {
  metadataBase?: T;
  siteName?: T;
  titleSuffix?: T;
  defaultRobotsIndex?: T;
  defaultRobotsFollow?: T;
  defaultTwitterCard?: T;
  defaultOgImageUrl?: T;
  defaultOgImageAlt?: T;
  serviceNotFoundTitle?: T;
  serviceItemNotFoundTitle?: T;
  organization?:
    | T
    | {
        name?: T;
        legalName?: T;
        url?: T;
        logoUrl?: T;
        telephone?: T;
        email?: T;
        foundingDate?: T;
        description?: T;
        priceRange?: T;
        founderName?: T;
        founderJobTitle?: T;
        addressLocality?: T;
        addressRegion?: T;
        addressCountry?: T;
        geoLatitude?: T;
        geoLongitude?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
        areaServed?:
          | T
          | {
              name?: T;
              type?: T;
              id?: T;
            };
        serviceCatalog?:
          | T
          | {
              name?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meta_select".
 */
export interface MetaSelect<T extends boolean = true> {
  brand?: T;
  profileImage?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  insta?: T;
  youtube?: T;
  tagline_footer?: T;
  instaFollowers?: T;
  youtubeSubscribers?: T;
  ownerName?: T;
  ownerRole?: T;
  yearOfEstablishment?: T;
  headquartersLocation?: T;
  googleMapsEmbed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}